# Generated by Django 3.0.5 on 2020-04-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search_music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=30)),
                ('m_name', models.CharField(max_length=1000)),
                ('play_url', models.CharField(max_length=1000)),
                ('Al_name', models.CharField(max_length=100)),
            ],
        ),
    ]
