# Generated by Django 3.0.5 on 2020-04-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_music',
            name='m_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='search_music',
            name='play_url',
            field=models.TextField(),
        ),
    ]
